name: xml lint

on:
  pull_request:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: XMLint  
        uses: ChristophWurst/xmllint-action@v1.2.1
        with:
          xml-file: github.workspace
          xml-schema-file: .xml
          
